import React from 'react';
import Head from 'next/head'
import cx from 'classnames';
import { Plus, MagnifyingGlass, Moon, Gift, Question, Rss, BookmarkSimple, Robot, Gear, List, Circle } from 'phosphor-react';
import type { NextPage } from 'next'
import Image from 'next/image';

import styles from '../styles/Home.module.css'
import Hover from '../components/Hover/Hover';
import logoSmall from '../assets/images/logo-small-2.png';
import lollipop from '../assets/images/lollipop.png';

const Home: NextPage = () => {
  return (
    <div className={styles.page}>
      <Head>
        <title>Vikash Gupta</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.container}>
        <div className={cx(styles.leftNavbar, styles.unselectable)}>
          <div className={styles.primary}>
            <div className={styles.head}>
              <div className={styles.logoContainer}>
                <Image src={logoSmall} alt="logo" height={32} width={32} />
              </div>
              <Hover disabled>
                <Circle color="#ffffff" size={24} weight="fill" className={styles.icon} />
              </Hover>
            </div>
            <div className={styles.mainOptions}>
              <Hover>
                <Plus size={24} className={styles.icon} />
              </Hover>
              <Hover>
                <MagnifyingGlass size={24} className={styles.icon} />
              </Hover>
              <Hover>
                <Moon size={24} className={styles.icon} />
              </Hover>
              <Hover>
                <Gift size={24} className={styles.icon} />
              </Hover>
              <Hover>
                <Question size={24} className={styles.icon} />
              </Hover>
            </div>
            <div className={styles.footer}>
              <Hover>
                <Circle color="#333333" size={32} weight="fill" className={styles.icon} />
              </Hover>
            </div>
          </div>
          <div className={styles.navList}>
            <div className={styles.navItem}>
              {/* <Rss size={20} weight="light" className={styles.navItemIcon} /> */}
              <Image src={lollipop} alt="logo" height={20} width={20} />
              <span>Hello, World!</span>
            </div>
            <div className={styles.navItem}>
              <BookmarkSimple size={20} weight="light" className={styles.navItemIcon} />
              <span>Bookmarks</span>
            </div>
            <div className={styles.navHeading}>
              <span>FEEDS</span>
              <Hover size="small">
                <Gear size={20} weight="light" className={styles.navItemIcon} />
              </Hover>
            </div>
            <div className={styles.navItem}>
              <List size={20} weight="light" className={styles.navItemIcon} />
              <span>All</span>
            </div>
            <div className={cx(styles.navItem, styles.lightText)}>
              <div className={styles.iconContainer}>
                <Circle color="#C5F6FA" size={10} weight="fill" className={styles.navItemIcon} />
              </div>
              <span>Books</span>
            </div>
            <div className={cx(styles.navItem, styles.lightText)}>
              <div className={styles.iconContainer}>
                <Circle color="#AFE6FA" size={10} weight="fill" className={styles.navItemIcon} />
              </div>
              <span>Entrepreneurship</span>
            </div>
            <div className={cx(styles.navItem, styles.lightText)}>
              <div className={styles.iconContainer}>
                <Circle color="#FDB196" size={10} weight="fill" className={styles.navItemIcon} />
              </div>
              <span>Ideas</span>
            </div>
            <div className={cx(styles.navItem, styles.lightText)}>
              <div className={styles.iconContainer}>
                <Circle color="#FF6961" size={10} weight="fill" className={styles.navItemIcon} />
              </div>
              <span>Productivity</span>
            </div>
            <div className={cx(styles.navItem, styles.lightText)}>
              <div className={styles.iconContainer}>
                <Circle color="#AAD6FA" size={10} weight="fill" className={styles.navItemIcon} />
              </div>
              <span>Tools</span>
            </div>
            <div className={styles.navHeading}>
              <span>BOARDS</span>
            </div>
          </div>
        </div>
        <div className={styles.subContent}></div>
        <div className={styles.content}></div>
      </div>
    </div>
  )
}

export default Home
